overlay = "."
crate_src_path = ".."
bin_name = "pve-xtermjs"

[source]
maintainer = "Proxmox Support Team <support@proxmox.com>"
section = "admin"
homepage = "http://www.proxmox.com"
vcs_git = "git://git.proxmox.com/git/pve-xtermjs.git"
vcs_browser = "https://git.proxmox.com/?p=pve-xtermjs.git;a=summary"

[package]
summary = "HTML/JS Shell client"
description = "This is an xterm.js client/proxy for Proxmox Hosts, PVE containers or QEMU Serial Terminals"
